#!/bin/sh

#
# History
#
# lec 03/18/2003
#	- SAO
#

cd `dirname $0` && . ./Configuration

cat - <<EOSQL | ${PG_DBUTILS}/bin/doisql.csh $0

DROP FUNCTION SP(int,int);

CREATE OR REPLACE FUNCTION SP (
)
RETURNS VOID AS
\$\$

DECLARE
v_userKey int;

BEGIN

IF NOT FOUND
THEN
	RAISE EXCEPTION E'';
	RETURN;
END IF;

END;
\$\$
LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION SP(int,int) TO public;

COMMENT ON FUNCTION mgd.SP(int,int) IS 'creates a new acc_accessionreference row';

EOSQL
