#!/bin/sh

cd `dirname $0` && . ./Configuration

${PG_MGD_DBSCHEMADIR}/procedure/SP_drop.object

cat - <<EOSQL | ${PG_DBUTILS}/bin/doisql.csh $0

CREATE OR REPLACE FUNCTION SP (
)
RETURNS VOID AS
\$\$

DECLARE
v_userKey int;

BEGIN

IF NOT FOUND
THEN
	RAISE EXCEPTION E'';
	RETURN;
END IF;

END;
\$\$
LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION SP(int,int) TO public;

COMMENT ON FUNCTION mgd.SP(int,int) IS '';

EOSQL
